"""tests/e2e/chaos/test_invalid_encoding.py — QUAL-15 scenario: a wrong-encoding file is detected,
never mis-decoded.

Reuses `tests/fixtures/corpus.yaml`'s `06_windows1250.csv` (CSV-02/CSV-03) as this test's source of
the actual cp1250 bytes: materialised via `tools.corpus.generators.generate_corpus` (the SAME
corpus-generation machinery `tests/e2e/slice/conftest.py`'s own `slice_fixtures_dir` fixture already
uses for a different manifest), never hand-authored. That fixture's own header (`id,miasto,kwota`,
3 columns) does not match any dataset currently configured on this live cluster (same
schema-incompatibility reasoning as `test_malformed_csv.py`'s own module docstring — read that
first) — worse, for THIS scenario specifically, `orders.yaml`'s `order_id`/`customer_id`/`amount`
columns are all real SQL `Integer`/`Numeric` columns (confirmed by reading
`migrations/versions/0016_normalized_orders.py`), so there is no dataset-column anywhere in
`orders` capable of carrying free text at all — `customers.yaml`'s `name`/`country` (real `text`
columns) are the ONLY live-configured place a Polish-diacritic string can flow all the way to a
database row. So this test reshapes `06_windows1250.csv`'s own generated field VALUES (its
Polish city picks, e.g. `"Łódź"`/`"Gdańsk"`/`"Żółkiewski"`) into `customers.yaml`'s real 5-column
header, preserving the encoding-detector-calibration-relevant bytes exactly
(`packages/csv-processor/src/csv_processor/detect/encoding.py`'s own module docstring names
`06_windows1250.csv`'s real generated bytes as the literal calibration data for this detector's
near-tie chardet/charset-normalizer correction — an arbitrary, differently-shaped Polish sample
risks not reliably clearing `DEFAULT_MIN_CONFIDENCE` at all, an irrelevant risk this test does not
need to accept).

Targets a NEW, dedicated `chaos_probe_discover_stage_publish_customers` DAG
(`airflow/dags/chaos_probe.py`, added by this same plan) rather than `csv_ingest_customers` itself:
at this plan's own execution time, `csv_ingest_customers` had a large pre-existing backlog
occupying its own `max_active_runs=1` budget for hours (see `test_malformed_csv.py`'s own module
docstring for the identical finding) — a NEW file uploaded to `raw/customers/` right now would
queue behind that backlog indefinitely, and `csv_ingest_customers.py`'s own production DAG file
must not be edited to work around it (that would either revert 10-07-PLAN.md's own OOM fix or
destabilise the platform's one real, continuously-scheduled customers pipeline). The probe DAG runs
the identical `dataplat discover`/`stage`/`publish` CLI commands the production DAG's own tasks
run, via the identical `_common/kpo.py` helper — same image, same ServiceAccount, same Vault
identity, genuinely live — just with no `wait_for_files`/`gate`/`dbt_build` bureaucracy and its own
independent `max_active_runs` budget.

No live, queryable place records `CsvProfile.encoding`/`.encoding_confidence`/`.encoding_source`
anywhere in `meta.files`/`meta.ingestion_runs` today (confirmed by reading every migration under
`migrations/versions/` for an `encoding`-named column -- none exists; `CsvProfile` is an in-memory
object `CsvSource.inspect()` returns, read only by `StagingLoader.load()`'s own
`schema_version_id` field, never persisted whole). So this test proves the "confidence score"
half of QUAL-15's own must-have truth by calling `csv_processor.detect.encoding.detect_encoding`
directly — the exact same production function `CsvSource.inspect()` itself calls, imported and
invoked here rather than duplicated — against the identical bytes this test uploads, and proves the
"never silently mis-decoded" half via the strongest possible live signal: a direct database query
confirming the diacritic-bearing `name` values that landed in `normalized.customers` are
BYTE-IDENTICAL to the fixture's own known-correct (UTF-8) strings, not mojibake.
"""

from __future__ import annotations

import contextlib
import csv as csv_module
import dataclasses
import io
import uuid
from pathlib import Path
from typing import TYPE_CHECKING, Any

import pytest
from tools.corpus.generators import generate_corpus
from tools.corpus.manifest import load_manifest

from csv_processor.detect.encoding import DEFAULT_MIN_CONFIDENCE, detect_encoding
from tests.e2e.slice.conftest import poll_file_discovered, poll_ingestion_run, poll_run_for_file

if TYPE_CHECKING:
    import subprocess
    from collections.abc import Callable

    import psycopg

pytestmark = [pytest.mark.cluster, pytest.mark.chaos]

_PROBE_DAG_ID = "chaos_probe_discover_stage_publish_customers"
_CUSTOMERS_DATASET = "customers"
_CORPUS_MANIFEST = Path(__file__).resolve().parents[2] / "fixtures" / "corpus.yaml"
_SOURCE_FIXTURE_NAME = "06_windows1250.csv"

_DISCOVERY_TIMEOUT_SECONDS = 300
_INGEST_TIMEOUT_SECONDS = 1800

# Fixed, valid, plain-ASCII values for the two customers.yaml columns 06_windows1250.csv's own
# generator never populates (that fixture has no birth_date/event_ts equivalent) -- ASCII-only, so
# they cannot perturb the cp1250 detection this test is actually proving.
_BIRTH_DATE = "1974-03-19"
_EVENT_TS = "2026-03-16T22:37:52Z"

# Customer_id window disjoint from every other live suite's own documented choice (module
# docstrings across tests/e2e/slice/*.py and tests/e2e/chaos/test_*.py).
_CUSTOMER_ID_BASE = 1_999_100_000


def _generate_source_fixture_bytes(tmp_path: Path) -> bytes:
    """Materialise `06_windows1250.csv` alone (never the full 69-fixture manifest) via
    `generate_corpus`.

    Filters the loaded manifest down to just this one fixture before calling `generate_corpus` --
    the same public API `slice_fixtures_dir` uses, just scoped to avoid generating (and paying the
    I/O cost of) every other corpus fixture this test does not need, including the deliberately
    huge `29_large_file.csv` profile.
    """
    manifest = load_manifest(_CORPUS_MANIFEST)
    selected = tuple(f for f in manifest.fixtures if f.name == _SOURCE_FIXTURE_NAME)
    assert len(selected) == 1, (
        f"expected exactly one {_SOURCE_FIXTURE_NAME!r} fixture declared in {_CORPUS_MANIFEST}, "
        f"found {len(selected)}"
    )
    filtered_manifest = dataclasses.replace(manifest, fixtures=selected)
    out_dir = tmp_path / "corpus"
    generate_corpus(filtered_manifest, out_dir, fast=True)
    return (out_dir / _SOURCE_FIXTURE_NAME).read_bytes()


def _reshape_into_customers_csv(source_bytes: bytes, *, marker: str) -> tuple[bytes, list[str]]:
    """Reshape `06_windows1250.csv`'s own generated rows into `customers.yaml`'s 5-column header.

    Reads the source fixture's real `id;miasto;kwota` rows (cp1250, `;`-delimited — decoded here
    only to iterate rows; `miasto`'s own diacritic bytes are carried through UNCHANGED into the
    rebuilt file, re-encoded with the identical `cp1250` codec) and emits
    `customer_id;name;country;birth_date;event_ts` rows: `customer_id` a fresh, uniquely-marked
    integer (`_CUSTOMER_ID_BASE` + row ordinal), `name` the source row's own `miasto` value
    (verbatim), `country` fixed `"PL"` (every `miasto` value is a real Polish city), `birth_date`/
    `event_ts` the fixed ASCII constants above.

    Args:
        source_bytes: `06_windows1250.csv`'s own generated bytes.
        marker: Unused directly (kept for call-site symmetry/clarity of intent) -- uniqueness comes
            from `_CUSTOMER_ID_BASE`, a fixed disjoint window, not from this marker; retained as a
            parameter so a future caller needing a content-level marker has an obvious place to add
            one without re-deriving this function's own row-shape logic.

    Returns:
        `(rebuilt_cp1250_bytes, expected_names)` — the second element is the ordered list of
        `miasto` values actually used, decoded to `str`, for this test's own later DB-round-trip
        assertion.
    """
    del marker  # See docstring -- uniqueness comes from _CUSTOMER_ID_BASE, not this marker.
    decoded = source_bytes.decode("cp1250")
    reader = csv_module.reader(io.StringIO(decoded), delimiter=";")
    header = next(reader)
    assert header == ["id", "miasto", "kwota"], f"unexpected 06_windows1250.csv header: {header!r}"

    out_lines = ["customer_id;name;country;birth_date;event_ts"]
    expected_names: list[str] = []
    for i, row in enumerate(reader):
        _source_id, miasto, _kwota = row
        customer_id = _CUSTOMER_ID_BASE + i
        out_lines.append(f"{customer_id};{miasto};PL;{_BIRTH_DATE};{_EVENT_TS}")
        expected_names.append(miasto)

    rebuilt_text = "\r\n".join(out_lines) + "\r\n"
    return rebuilt_text.encode("cp1250"), expected_names


def test_windows1250_customers_file_is_detected_and_correctly_decoded(
    tmp_path: Path,
    s3_client: Callable[[str], Any],
    analytics_connection: psycopg.Connection[Any],
    kubectl: Callable[..., subprocess.CompletedProcess[str]],
) -> None:
    """CSV-02/CSV-03, live: cp1250 is detected (not the default UTF-8), and every diacritic
    survives.

    Uploads the reshaped cp1250 file, triggers `chaos_probe_discover_stage_publish_customers`, waits
    for the run to reach `SUCCEEDED`, then asserts: (1) `csv_processor.detect.encoding.
    detect_encoding` (the real production detector, called directly against the exact uploaded
    bytes) reports a cp1250-family encoding at `source='detected'` with confidence strictly between
    `DEFAULT_MIN_CONFIDENCE` and `1.0` — never `1.0` (no BOM/contract override exists for this
    file), never `'undetermined'` (a confidence below the module's own floor); (2) every row's
    `name` value in `normalized.customers`, read back directly, is BYTE-IDENTICAL to the fixture's
    own original (UTF-8-domain) Polish city string — proving the live pipeline decoded with cp1250,
    not silently mis-decoded (e.g. as Windows-1252/ISO-8859, which would corrupt these exact bytes
    differently) or raised.
    """
    app = s3_client("app")
    admin = s3_client("admin")

    source_bytes = _generate_source_fixture_bytes(tmp_path)
    marker = uuid.uuid4().hex[:12]
    payload, expected_names = _reshape_into_customers_csv(source_bytes, marker=marker)

    # Real production detection, against the EXACT bytes this test is about to upload -- the same
    # bounded-sample call `CsvSource.inspect()` itself makes (module docstring: no live-queryable
    # place records this today, so this is the closest live proof of the "confidence score" half of
    # QUAL-15's own must-have truth for this scenario).
    detection = detect_encoding(payload, contract_encoding=None)
    assert detection.source == "detected", (
        f"expected source='detected' (no BOM, no contract override), got {detection.source!r} "
        f"(encoding={detection.encoding!r}, confidence={detection.confidence!r})"
    )
    normalized_encoding = detection.encoding.replace("-", "").replace("_", "").lower()
    assert normalized_encoding in {"cp1250", "windows1250"}, (
        f"expected a cp1250-family encoding, got {detection.encoding!r}"
    )
    assert DEFAULT_MIN_CONFIDENCE < detection.confidence < 1.0, (
        f"expected confidence strictly between {DEFAULT_MIN_CONFIDENCE} and 1.0 (a genuine, "
        f"non-certain detection -- 06_windows1250.csv's own corpus.yaml expect: block declares "
        f"encoding_confidence_max: 0.99), got {detection.confidence!r}"
    )

    key = f"customers/e2e-chaos-encoding-{marker}.csv"
    object_uri = f"s3://raw/{key}"
    run_id_marker = f"e2e-chaos-encoding-{marker}"

    try:
        unpause = kubectl(
            "-n",
            "airflow",
            "exec",
            "deploy/airflow-api-server",
            "--",
            "airflow",
            "dags",
            "unpause",
            _PROBE_DAG_ID,
        )
        assert unpause.returncode == 0, f"airflow dags unpause failed:\n{unpause.stderr}"

        app.put_object(Bucket="raw", Key=key, Body=payload)

        trigger = kubectl(
            "-n",
            "airflow",
            "exec",
            "deploy/airflow-api-server",
            "--",
            "airflow",
            "dags",
            "trigger",
            _PROBE_DAG_ID,
            "--run-id",
            run_id_marker,
        )
        assert trigger.returncode == 0, f"airflow dags trigger failed:\n{trigger.stderr}"

        file_row = poll_file_discovered(
            analytics_connection,
            dataset=_CUSTOMERS_DATASET,
            object_uri=object_uri,
            timeout=_DISCOVERY_TIMEOUT_SECONDS,
        )
        assert file_row["duplicate_of_file_id"] is None, (
            f"the freshly-marked fixture was already flagged a duplicate of file_id="
            f"{file_row['duplicate_of_file_id']!r}"
        )

        run_row = poll_run_for_file(analytics_connection, file_id=file_row["file_id"], timeout=60)
        outcome = poll_ingestion_run(
            analytics_connection,
            run_row["idempotency_key"],
            timeout=_INGEST_TIMEOUT_SECONDS,
        )
        assert outcome["status"] == "SUCCEEDED", (
            f"run {run_row['idempotency_key']!r} finished {outcome['status']!r}, not SUCCEEDED"
        )

        customer_id_low = _CUSTOMER_ID_BASE
        customer_id_high = _CUSTOMER_ID_BASE + len(expected_names) - 1
        with analytics_connection.cursor() as cur:
            cur.execute(
                "SELECT customer_id, name FROM normalized.customers "
                "WHERE customer_id BETWEEN %s AND %s ORDER BY customer_id",
                (customer_id_low, customer_id_high),
            )
            loaded = cur.fetchall()
        assert len(loaded) == len(expected_names), (
            f"expected {len(expected_names)} rows in normalized.customers for customer_id in "
            f"[{customer_id_low}, {customer_id_high}], found {len(loaded)}"
        )
        actual_names = [row[1] for row in loaded]
        assert actual_names == expected_names, (
            f"decoded name values do not match the fixture's own original Polish city strings -- "
            f"a silent mis-decode occurred.\nexpected: {expected_names!r}\n"
            f"actual:   {actual_names!r}"
        )
    finally:
        with contextlib.suppress(Exception):
            admin.delete_object(Bucket="raw", Key=key)
