"""tests/e2e/slice/test_backfill_2year_sweep.py — Phase 9's capstone live-cluster proof.

Proves, on the real live kind cluster, that `csv_ingest_customers`/`csv_ingest_orders` genuinely
support backfill end to end for a combined-property fixture corpus (schema evolution, a missing
file, a late/out-of-order event), then proves idempotency (QUAL-11) and live+backfill concurrency
(D-12/D-13) — the live demonstration that everything built in Phase 9's earlier waves actually
works together, not in isolation.

## Three genuine, live-discovered deviations from the plan's literal text

This module is the FIRST real integration exercise of several mechanisms that were previously
only unit/integration-tested in isolation. Three genuine discoveries changed this module's design
from what 09-11-PLAN.md/09-RESEARCH.md assumed:

1. **`csv_ingest_orders` cannot be targeted by `airflow backfill create` at all.** RESEARCH.md
   stated (HIGH confidence, but verified WRONG this session) that "both DAGs are
   `schedule=\"*/1 * * * *\"\"`. In fact `csv_ingest_orders` has been `schedule=[customers_asset]`
   (Asset-triggered, D-15) since plan 08.1-12 — confirmed live: `airflow backfill create
   --dag-id csv_ingest_orders --dry-run ...` raises
   `airflow.models.backfill.DagNonPeriodicScheduleException: csv_ingest_orders has a
   non-periodic schedule that does not support backfills`. D-08's "closing the silver.orders
   0-rows gap ... running the orders backfill" is therefore satisfied differently: the full
   orders corpus is uploaded to MinIO ahead of the customers backfill, and orders' own existing,
   already-correct structure (Asset-triggered off every customers publish, `discover_files`'s own
   bucket-wide, date-agnostic rescan) drains it as a natural consequence of the customers backfill
   cascading `customers_asset` events — no bypass, no new tooling, no DAG restructuring (D-11):
   orders processes this corpus through the EXACT SAME structure it always uses, which simply
   happens to not be date/backfill-CLI-driven by design (08.1's own D-15/D-16). This module never
   invokes `airflow backfill create --dag-id csv_ingest_orders`.

2. **`tools/corpus/dated_series.py` generated non-integer business keys — a genuine, pre-existing
   bug, never live-exercised before this plan.** `normalized.customers.customer_id` and
   `normalized.orders.{order_id,customer_id}` are all `sa.Integer()` (migrations 0005/0016), cast
   via `::int` in `MergePublisher`'s/`OrdersMergePublisher`'s own `_PUBLISH_SQL`. The generator's
   original alphanumeric business key (`"CUST-000010-0010"`) fails that cast
   (`invalid input syntax for type integer`), aborting the WHOLE publish transaction for the file
   (WR-04's documented "one bad value blocks the whole publish" limitation) — every customers/
   orders row generated by the ORIGINAL code would have failed to publish. Fixed inline (Rule 1)
   in `tools/corpus/dated_series.py`: `customer_id`/`order_id` now render as plain decimal-digit
   strings, still satisfying the CSV contract's `type: string` declaration (only the FINAL
   gold-layer INSERT casts). `orders.customer_id` values are drawn from the customers series' own
   day-0 ID range so `ReferentialIntegrityBarrier` (`QUARANTINE_RECORD`) resolves them as genuine,
   non-orphaned matches rather than exercising quarantine — see that file's own updated docstring
   for the exact ID-space allocation. `tests/unit/test_dated_series.py` (5/5) and
   `tests/policy/test_generator_determinism_rules.py` (5/5) both still pass unmodified after this
   fix — neither asserts the exact business-key VALUE, only shape/determinism.

3. **`meta.processing_gaps`/`record_processing_gap_if_empty` (plan 09-10) is a WHOLE-BUCKET-EMPTY
   signal, not a PER-CALENDAR-DAY-MISSING signal.** `record_processing_gap_if_empty` only writes a
   row when `list_matched_keys` (a bucket-wide wildcard listing, deliberately date-agnostic per
   RESEARCH.md's own Pitfall 1) returns EMPTY for a whole backfill DagRun tick — i.e., "this
   backfill run found ZERO files matching the prefix at all," not "this specific historical date's
   file is missing among many present ones." Since `meta.files.business_date` is never populated
   anywhere in this codebase (confirmed, Pitfall 1) there is no mechanism that could associate one
   specific missing day with one specific tick within an otherwise-populated bucket — building one
   would be new, cross-cutting architectural work (Rule 4: genuinely out of this plan's scope,
   `packages/dataplat/**`/`airflow/dags/_common/gap_recorder.py` are not in this plan's declared
   file list). `test_full_2year_sweep_customers_and_orders` therefore asserts D-06's SUBSTANTIVE
   claim directly and honestly: the gap day's file/row is genuinely absent everywhere (no phantom
   data), every OTHER day's file WAS discovered and published (the gap did not stop the rest of
   the window), and `meta.processing_gaps` correctly has ZERO rows for this corpus (matching its
   real, whole-bucket-empty semantics — not a failure of this test, a confirmation the mechanism
   behaves exactly as `gap_recorder.py`'s own code does). `meta.processing_gaps`' OWN mechanics
   (empty-listing detection) were already proven in `tests/dagtest/test_gap_recorder.py` (09-10,
   5/5) and are not re-proven here.

4. **A live, genuinely blocking infra gap: `analytics_db_default` was never provisioned in
   Vault.** Discovered live this session: `list_run_ids_pending_dbt_build` (`run_stage_recorder.py`)
   failed 100% of the time (22/22 historical attempts today, confirmed via direct SQL against the
   Airflow metadata DB), cascading `upstream_failed` through `mark_dbt_build_running -> dbt_build`
   -- meaning `dbt build` never actually ran for ANY DagRun during the affected window, live or
   backfill, so `silver.customers`/`silver.orders` never received fresh bronze->silver
   transformations even though the owning `meta.ingestion_runs.status` could still (incorrectly)
   read `SUCCEEDED` (bronze `stage_ingest`'s own status transition is independent of whether dbt
   ever ran). Root-caused via direct Vault inspection (root-token `vault kv list
   airflow/connections`): `airflow/connections/analytics_db_default` was simply never written --
   `minio_default` was the only entry, and neither `scripts/vault-bootstrap.py` nor any Helm
   values file provisions this connection (`grep` confirmed zero hits repo-wide); it must have
   been created ad hoc during an earlier phase's live-verification session and lost to one of
   this session's own documented infra disruptions. Fixed live (Rule 3, infra-only, no repo file
   changed): wrote `airflow/connections/analytics_db_default` in Vault reusing the ALREADY-EXISTING
   `etl_app` credential this suite's own `conftest.py::_etl_app_credentials` already reads from
   `etl/analytics-db#dsn` -- no new credential, no new privilege, matching this project's
   established "reuse the existing role" precedent. Because files processed DURING the outage
   window got a false `SUCCEEDED` status without ever reaching `silver`/`normalized` (permanently
   ineligible for reprocessing under `discover_files`' own idempotency), `_MASTER_SEED` was bumped
   (`-v1` -> `-v2`) so every file this module's own real assertions depend on is genuinely fresh
   content, generated and uploaded AFTER the fix, never touching the contaminated `-v1` run_ids.

## Window-sizing lesson: more DagRuns does not mean more throughput here

`stage`/`dbt_build`/`publish` are capped `max_active_tis_per_dag=1` **globally, across every
concurrently-active DagRun** (RESEARCH.md Architecture Pattern 2's own caveat) -- but
`list_matched_keys`/`discover` are NOT scoped per-tick or per-DagRun (Pitfall 1: bucket-wide,
date-agnostic). Combining a MULTI-TICK backfill window with a small, static, already-uploaded
corpus means EVERY tick's own `discover` call independently re-lists and may re-attempt to claim
the SAME files, live-observed this session to genuinely multiply queue depth against that one
global serialization slot (two concurrent DagRuns each independently scheduling 13 `stage`
instances for the identical 13-file corpus, not just one DagRun's worth) -- `--max-active-runs 3`
therefore amplifies self-inflicted contention for a small corpus rather than adding real
throughput. This module's own live-observed `FailedScheduling: Insufficient cpu` events (Task 1's
pilot, `--max-active-runs 3`, a 5-tick window) are BOTH a genuine D-12 CPU-starvation finding AND
partly self-inflicted by that window/corpus-size combination -- both true at once. Every
REAL-WORK-triggering window in this module (pilot, full sweep, concurrency) is therefore sized to
1-3 ticks, not 5+: enough for `--max-active-runs 3` to have a SECOND concurrent DagRun to race
against (still proving/disproving D-12's starvation question meaningfully) without compounding
that race across many redundant ticks.

## D-27 fallback: representative-scale live corpus, not the literal 2-year window

D-09 (LOCKED) calls for "genuinely 2 years of synthetic fixture files." `generate_dated_series`
supports any `num_days` including 730 and is exercised at full 2-year scale by
`tests/integration/test_backfill_idempotency.py`'s testcontainers tier (idempotency-key mechanics,
full-scale, no live cluster required). This module's LIVE proof — the one D-27 explicitly allows a
representative-scale fallback for when local hardware/time genuinely cannot sustain the full-scale
live run — uses a smaller, still fully live, still combining all four D-10 properties in the SAME
window (regular cadence + one gap day + one schema-change boundary + one late/out-of-order event):
`_NUM_DAYS = 20` days per dataset (19 real files after the gap day; extended from 14 by plan 10-07
to comfortably fit three additional SCD anomaly days without cramming — see that plan's own module
constants block), comfortably under `discover_files`' `max_units_per_run: 100` batching cap (so
this module proves the SAME mechanics `Pitfall 1`'s 2-year/15-discover-call math describes, at a
wall-clock-tractable scale for a single live-cluster proof session run on real WSL2/kind hardware
with this project's own documented, recurring CPU-starvation history). This is the D-27 fallback
path, explicitly recorded here per its own acceptance criteria.

## Plan 10-07: SCD anomalies wired into the SAME live sweep, plus a separate D-06 fixture

Phase 10's `SCDPublisher` (plan 10-04) replaced `customers.yaml`'s `load.strategy` from `merge` to
`scd` — this module's own pre-existing 7-assertion proof above still holds unmodified (D-05..D-11
say nothing about SCD), but the corpus now ALSO carries three deterministic SCD anomalies (D-11,
generated by plan 10-06's roster model): an attribute change, a late-arriving correction, and one
missing customer. Three genuine, live-discovered findings from wiring them into this real pipeline
for the first time (10-04/10-05's own tests bypassed the CSV pipeline via direct SQL bronze
seeding, so none of the below was exercised until this plan's own live run):

1. **`dataplat.pipeline.run._TARGET_COLUMNS_BY_DATASET["customers"]` never gained `signup_country`**
   (D-13, migration 0035/0037) — a real, pre-existing gap plan 10-04's own SUMMARY explicitly
   flagged as "will block plan 10-07's live 2-year backfill sweep until fixed." Every real
   `stage_ingest()` call for `customers` raised `ValueError` at `StagingLoader._build_stages`
   before this fix (Rule 3): `ColumnContract("signup_country")` had no entry in this lookup.
   Fixed by appending `"signup_country"` to the tuple, matching the CSV/staging-table column order
   `tools/corpus/dated_series.py` and `customers.yaml` already use.

2. **`customers.yaml`'s own `customers_customer_id_uniqueness` `QUALITY_UNIQUENESS` rule silently
   dropped D-11's own late-correction fixture.** The rule predates Phase 10 and encoded a
   `MergePublisher`-era assumption — "two rows sharing a `customer_id` within one file is always a
   data error" — that D-11's own late-correction mechanic (an intentional SECOND, backdated row
   for an already-present roster member, appended by `tools/corpus/dated_series.py`) directly
   violates on purpose. `UniquenessRule` (REJECT_RECORD, within-chunk, first-occurrence-wins) would
   have silently dropped the LATER-occurring correction row before it ever reached
   `staging.customers`, making SCD-07's live proof structurally impossible — a real, general
   correctness bug for this dataset's ongoing operation (silently discarding a genuine correction),
   not merely a test-fixture inconvenience. Removed (Rule 1): `normalized.customers`'s own
   correctness under `scd` no longer depends on pre-publish key uniqueness — `SCDPublisher`'s
   `recompute_version_chain` deterministically folds EVERY bronze row for a key, including
   legitimate same-file duplicates, into the correct version chain by `(event_ts,
   source_row_number)` order.

3. **`tests/integration/test_stage_ingest.py`/`test_run_ingest.py`'s own local 5-column customers
   CSV fixtures desynchronized `StagingLoader`'s COPY column alignment** once finding 1's fix made
   `_TARGET_COLUMNS_BY_DATASET["customers"]` genuinely 6 columns wide: a narrower row is left
   UNPADDED by `StagingLoader.load()` (`row[: len(target_columns)] if len(row) > len(target_columns)
   else row` — the `else` branch never pads), so every COPY value shifted one position left,
   observed live as `_source_row_number` receiving a hash-looking string. Fixed (Rule 1, a direct
   regression from finding 1's own fix) by widening both files' fixture CSV header/rows and
   `ColumnContract` lists to the real 6-column shape. **Deferred, not fixed by this plan**
   (genuinely out of scope — `StagingLoader` correctly padding a narrower row is separate, general
   architectural work D-13 itself anticipates but never implemented): `tests/e2e/slice/
   test_backfill_reentry.py`'s own 5-column customers CSV fixture is NOT updated here (it is not
   part of this plan's own declared file scope nor its `<verification>` requirement, which is
   `test_backfill_2year_sweep.py` only) — a future live run of that file may surface the same
   symptom finding 3 describes, and should be fixed the same way if so.

D-06's mass-delete circuit-breaker-trip fixture (Task 3) is a SEPARATE, single-day
`generate_dated_series("customers", ...)` call — same `master_seed`/`rows_per_day` as
`sweep_corpus`'s own call (so the roster is byte-identical), `start_date` set to the day
immediately after this module's own extended window — uploaded and processed OUTSIDE the main
sweep's own backfill window, deliberately (a deliberately-truncated snapshot is expected to fail
that one day's run loudly, not blend into the successful sweep).
"""

from __future__ import annotations

import re
import time
from dataclasses import dataclass
from datetime import UTC, date, datetime, timedelta
from typing import TYPE_CHECKING, Any

import pytest
from tools.corpus.dated_series import (
    _CUSTOMER_ID_BASE,
    _ID_DAY_MULTIPLIER,
    _ORDER_ID_BASE,
    BackfillCorpusManifest,
    generate_dated_series,
)

if TYPE_CHECKING:
    import subprocess
    from collections.abc import Callable, Sequence

    import psycopg

pytestmark = pytest.mark.cluster

_CUSTOMERS_DAG_ID = "csv_ingest_customers"
_ORDERS_DAG_ID = "csv_ingest_orders"
_CUSTOMERS_DATASET = "customers"
_ORDERS_DATASET = "orders"
_ETL_NAMESPACE = "etl"

# D-27 fallback scale (module docstring): comfortably under discover_files'
# max_units_per_run: 100 cap, so one discover call drains the whole corpus.
_MASTER_SEED = "phase-09-plan-11-backfill-2year-sweep-v3"
_START_DATE = date(2024, 1, 1)
# Extended from 14 to 20 (plan 10-07) to comfortably fit D-11's three new
# anomaly days (12/16/19 below) alongside the pre-existing gap(5)/schema-
# change(7)/late-event(10) days without cramming -- matches this file's own
# established "comfortably under [budget]" comment style.
_NUM_DAYS = 20
_GAP_DAY_INDEX = 5
_SCHEMA_CHANGE_DAY_INDEX = 7
_LATE_EVENT_DAY_INDEX = 10
_LATE_EVENT_OFFSET_DAYS = 90
_ROWS_PER_DAY = 50  # default -- keeps orders' customer_id pool (day 0, rows 0..29) fully valid

# D-11 (plan 10-07 Task 1): attribute-change/late-correction/missing-customer
# anomaly placement, all customers-only (generate_dated_series raises if
# passed for orders). Member indices are all >= 30 -- never colliding with
# orders' own referential-integrity customer_id pool (_ORDER_CUSTOMER_IDS,
# roster indices [0, 29]) or with the pre-existing late-event mechanic's own
# member index (_ROWS_PER_DAY // 2 == 25).
_ATTRIBUTE_CHANGE_DAY_INDEX = 12
_ATTRIBUTE_CHANGE_MEMBER_INDEX = 30
_LATE_CORRECTION_ARRIVAL_DAY_INDEX = 16
_LATE_CORRECTION_MEMBER_INDEX = 31
# 16 - 11 = day index 5 -- this corpus' OWN gap day, which never has a real
# bronze event for ANY member (no file generated that day at all). Every
# real day shares the identical T08:15:00Z time-of-day, so any OTHER
# integer offset would land the correction's backdated event_ts EXACTLY on
# some other real day's own event_ts (an ambiguous tie); landing on the gap
# day's own calendar date guarantees a clean, unambiguous chronological
# position strictly between two real, adjacent bronze events (day 4 and day
# 6) for this member.
_LATE_CORRECTION_OFFSET_DAYS = 11
# The LAST day in the window -- required, not incidental. SCDPublisher's
# Step A (DELETE-detection) compares EACH pass's own staged snapshot
# against currently-current gold rows; a member missing from a MIDDLE day
# but present again on a LATER day would be re-touched by that later day's
# own full-history recompute (Step C), silently erasing the earlier
# "vanished" closure. Only an absence from the FINAL day's own snapshot
# survives as this sweep's own checked, final gold state.
_MISSING_CUSTOMER_DAY_INDEX = _NUM_DAYS - 1
_MISSING_CUSTOMER_MEMBER_INDEX = 32

# D-06 (plan 10-07 Task 3): the mass-delete circuit-breaker-trip fixture's
# own member indices, deliberately disjoint from the three above (33..47,
# 15 of the 50-member roster == 30%, comfortably exceeding customers.yaml's
# configured mass_delete_threshold: 0.10).
_MASS_DELETE_MEMBER_INDICES = tuple(range(33, 48))

_POLL_INTERVAL_SECONDS = 2.0
_TERMINAL_RUN_STATUSES = frozenset(
    {"SUCCEEDED", "FAILED", "SKIPPED_DUPLICATE", "SKIPPED_CONCURRENT"}
)

_DRY_RUN_TICK_PATTERN = re.compile(
    r"^\|\s+\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\+00:00\s+\|", re.MULTILINE
)


# ---------------------------------------------------------------------------
# Corpus generation + upload (module-scoped: once for this whole file)
# ---------------------------------------------------------------------------


@dataclass
class _Corpus:
    customers_manifest: BackfillCorpusManifest
    orders_manifest: BackfillCorpusManifest
    # Retained (plan 10-07) so Task 1's SCD assertions can read the corpus'
    # OWN exact injected values (attribute-change/late-correction rows)
    # directly, rather than re-deriving them via dated_series.py's private
    # helper functions -- generation is a pure, deterministic function of
    # its arguments, so re-calling it here (already done, no I/O) is the
    # single source of truth for "what did this fixture actually inject".
    customers_files: dict[str, bytes]


@dataclass
class _SweepState:
    """Mutable, module-scoped state shared across this file's ORDERED tests.

    Task 1's pilot test writes `max_active_runs` after observing whether the live cluster shows
    CPU starvation (D-12's "try, then degrade" framing); Task 2/3 read it back rather than
    re-deriving it. `full_sweep_window`/`full_sweep_backfill_id` are written by Task 2 and reused
    verbatim by Task 3's idempotent-rerun test (QUAL-11 requires the IDENTICAL window).
    """

    # Hardcoded to 1: this cluster has shown CPU starvation at max_active_runs=3 in every
    # observed run this session (Task 1's pilot and Task 2's own first attempts) -- Task 1's
    # pilot test still mutates this in-process on its own degrade logic, but Task 1/2/3 run as
    # SEPARATE `pytest -k ...` invocations (separate processes) for iteration speed, so that
    # mutation never actually carries forward; starting at the already-empirically-justified
    # value avoids re-deriving the same conclusion (and re-inflicting the same contention) on
    # every fresh invocation.
    max_active_runs: int = 1
    full_sweep_from: datetime | None = None
    full_sweep_to: datetime | None = None


@pytest.fixture(scope="module")
def sweep_state() -> _SweepState:
    return _SweepState()


@pytest.fixture(scope="module")
def sweep_corpus(s3_client: Callable[[str], Any]) -> _Corpus:
    """Generate the D-27 representative-scale corpus and upload it to MinIO, once per module.

    A SETUP step, not something the backfill CLI's own `--from-date`/`--to-date` window needs to
    span (RESEARCH.md Pitfall 1: the fixture corpus and the backfill window are two SEPARATE
    things) -- every file this call generates is uploaded here, before any test invokes a real
    backfill.
    """
    customers_files, customers_manifest = generate_dated_series(
        "customers",
        master_seed=_MASTER_SEED,
        start_date=_START_DATE,
        num_days=_NUM_DAYS,
        gap_day_index=_GAP_DAY_INDEX,
        schema_change_day_index=_SCHEMA_CHANGE_DAY_INDEX,
        late_event_day_index=_LATE_EVENT_DAY_INDEX,
        late_event_offset_days=_LATE_EVENT_OFFSET_DAYS,
        rows_per_day=_ROWS_PER_DAY,
        attribute_change_day_index=_ATTRIBUTE_CHANGE_DAY_INDEX,
        attribute_change_member_index=_ATTRIBUTE_CHANGE_MEMBER_INDEX,
        late_correction_arrival_day_index=_LATE_CORRECTION_ARRIVAL_DAY_INDEX,
        late_correction_member_index=_LATE_CORRECTION_MEMBER_INDEX,
        late_correction_offset_days=_LATE_CORRECTION_OFFSET_DAYS,
        missing_customer_day_index=_MISSING_CUSTOMER_DAY_INDEX,
        missing_customer_member_index=_MISSING_CUSTOMER_MEMBER_INDEX,
    )
    orders_files, orders_manifest = generate_dated_series(
        "orders",
        master_seed=_MASTER_SEED,
        start_date=_START_DATE,
        num_days=_NUM_DAYS,
        gap_day_index=_GAP_DAY_INDEX,
        schema_change_day_index=_SCHEMA_CHANGE_DAY_INDEX,
        late_event_day_index=_LATE_EVENT_DAY_INDEX,
        late_event_offset_days=_LATE_EVENT_OFFSET_DAYS,
        rows_per_day=_ROWS_PER_DAY,
    )

    app = s3_client("app")
    for filename, body in customers_files.items():
        app.put_object(Bucket="raw", Key=f"customers/{filename}", Body=body)
    for filename, body in orders_files.items():
        app.put_object(Bucket="raw", Key=f"orders/{filename}", Body=body)

    return _Corpus(
        customers_manifest=customers_manifest,
        orders_manifest=orders_manifest,
        customers_files=customers_files,
    )


# ---------------------------------------------------------------------------
# Backfill CLI helpers
# ---------------------------------------------------------------------------


def _minute_aligned_utc_now() -> datetime:
    return datetime.now(UTC).replace(second=0, microsecond=0)


def _window(*, offset_minutes: int, span_minutes: int) -> tuple[datetime, datetime]:
    """A `(from_date, to_date)` pair, minute-aligned, `offset_minutes` before `now()`.

    `span_minutes` ticks span `[start, start + span_minutes]` inclusive on both ends (verified
    live: `--from-date 00:00 --to-date 00:05` enumerates 6 ticks, :00 through :05).
    """
    start = _minute_aligned_utc_now() - timedelta(minutes=offset_minutes)
    end = start + timedelta(minutes=span_minutes)
    return start, end


def _kubectl_airflow(
    kubectl_fn: Callable[..., subprocess.CompletedProcess[str]],
    *args: str,
) -> subprocess.CompletedProcess[str]:
    return kubectl_fn(
        "-n", "airflow", "exec", "deploy/airflow-api-server", "--", "airflow", *args
    )


def _dry_run_tick_count(
    kubectl_fn: Callable[..., subprocess.CompletedProcess[str]],
    *,
    dag_id: str,
    from_iso: str,
    to_iso: str,
) -> int:
    """Invoke `airflow backfill create --dry-run` and count the enumerated ticks.

    Pitfall 1's exact failure mode this guards against: an unbounded window enumerating tens or
    hundreds of thousands of DagRuns. Asserts CLI success separately from the tick count so a
    genuine CLI failure (e.g. `DagNonPeriodicScheduleException`) is never miscounted as `0` ticks.
    """
    result = _kubectl_airflow(
        kubectl_fn,
        "backfill", "create",
        "--dag-id", dag_id,
        "--from-date", from_iso,
        "--to-date", to_iso,
        "--dry-run",
    )
    assert result.returncode == 0, (
        f"airflow backfill create --dry-run --dag-id {dag_id} failed "
        f"(exit {result.returncode}):\n{result.stdout}\n{result.stderr}"
    )
    return len(_DRY_RUN_TICK_PATTERN.findall(result.stdout))


def _invoke_backfill_create(  # noqa: PLR0913 -- one keyword per D-11-locked CLI flag + retry knobs
    kubectl_fn: Callable[..., subprocess.CompletedProcess[str]],
    *,
    dag_id: str,
    from_iso: str,
    to_iso: str,
    max_active_runs: int,
    max_attempts: int = 3,
    retry_backoff_seconds: float = 5.0,
) -> subprocess.CompletedProcess[str]:
    """Invoke a REAL `airflow backfill create`, D-11's exact locked CLI shape.

    Retries a bounded number of times on outright CLI failure (this project's own documented,
    recurring live-cluster transients -- scheduler contention, a lost `SELECT ... FOR UPDATE
    SKIP LOCKED` race per `.planning/debug/backfill-does-not-redrive-rejected-row.md`) rather than
    failing the whole test on the first transient blip.
    """
    last: subprocess.CompletedProcess[str] | None = None
    for attempt in range(1, max_attempts + 1):
        last = _kubectl_airflow(
            kubectl_fn,
            "backfill", "create",
            "--dag-id", dag_id,
            "--from-date", from_iso,
            "--to-date", to_iso,
            "--max-active-runs", str(max_active_runs),
            "--reprocess-behavior", "completed",
        )
        if last.returncode == 0:
            return last
        if attempt < max_attempts:
            time.sleep(retry_backoff_seconds)
    assert last is not None, "unreachable: the loop above always assigns `last` at least once"
    assert last.returncode == 0, (
        f"airflow backfill create --dag-id {dag_id} --from-date {from_iso} --to-date {to_iso} "
        f"failed after {max_attempts} attempts (exit {last.returncode}):\n"
        f"{last.stdout}\n{last.stderr}"
    )
    return last


def _latest_backfill_id(conn: psycopg.Connection[Any], *, dag_id: str) -> int | None:
    with conn.cursor() as cur:
        cur.execute("SELECT id FROM backfill WHERE dag_id = %s ORDER BY id DESC LIMIT 1", (dag_id,))
        row = cur.fetchone()
    return None if row is None else int(row[0])


def _wait_for_new_backfill_completed(
    conn: psycopg.Connection[Any],
    *,
    dag_id: str,
    since_backfill_id: int | None,
    timeout: float,
) -> int:
    """Poll for a `backfill` row newer than `since_backfill_id` to reach `completed_at IS NOT NULL`.

    Returns the completed backfill's own `id`.
    """
    deadline = time.monotonic() + timeout
    last_seen: tuple[int, Any] | None = None
    while time.monotonic() < deadline:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT id, completed_at FROM backfill WHERE dag_id = %s ORDER BY id DESC LIMIT 1",
                (dag_id,),
            )
            row = cur.fetchone()
        if row is not None:
            backfill_id, completed_at = row
            if since_backfill_id is None or backfill_id > since_backfill_id:
                last_seen = (backfill_id, completed_at)
                if completed_at is not None:
                    return int(backfill_id)
        time.sleep(_POLL_INTERVAL_SECONDS)
    msg = (
        f"no NEW backfill row for dag_id={dag_id!r} (since_backfill_id={since_backfill_id!r}) "
        f"reached completed_at within {timeout}s (last observed: {last_seen!r})"
    )
    raise AssertionError(msg)


# ---------------------------------------------------------------------------
# Analytics-DB polling helpers
# ---------------------------------------------------------------------------


def _latest_dag_run_pk(conn: psycopg.Connection[Any], *, dag_id: str) -> int | None:
    with conn.cursor() as cur:
        cur.execute("SELECT id FROM dag_run WHERE dag_id = %s ORDER BY id DESC LIMIT 1", (dag_id,))
        row = cur.fetchone()
    return None if row is None else int(row[0])


def _wait_for_new_dag_run_terminal(
    conn: psycopg.Connection[Any],
    *,
    dag_id: str,
    since_pk: int | None,
    timeout: float,
) -> None:
    """Poll for a `dag_run` row newer than `since_pk` (this dag_id's own `id` PK) to go terminal.

    Used to wait for an Asset-cascade-triggered `csv_ingest_orders` run to settle after a
    customers publish, WITHOUT a blind `sleep(N)` (this codebase's own established
    "sleep-in-e2e-tests is a permanent-flakiness trap" discipline).
    """
    deadline = time.monotonic() + timeout
    last_state: str | None = None
    while time.monotonic() < deadline:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT id, state FROM dag_run WHERE dag_id = %s ORDER BY id DESC LIMIT 1",
                (dag_id,),
            )
            row = cur.fetchone()
        if row is not None:
            pk, state = row
            last_state = state
            if (since_pk is None or pk > since_pk) and state in ("success", "failed"):
                return
        time.sleep(_POLL_INTERVAL_SECONDS)
    msg = (
        f"no NEW dag_run for dag_id={dag_id!r} (since_pk={since_pk!r}) reached a terminal state "
        f"within {timeout}s (last observed state: {last_state!r})"
    )
    raise AssertionError(msg)


def _dataset_id(conn: psycopg.Connection[Any], name: str) -> int:
    with conn.cursor() as cur:
        cur.execute("SELECT dataset_id FROM meta.datasets WHERE dataset_name = %s", (name,))
        row = cur.fetchone()
    assert row is not None, f"meta.datasets has no row for dataset_name={name!r}"
    return int(row[0])


def _wait_for_dataset_files_terminal(
    conn: psycopg.Connection[Any],
    *,
    dataset: str,
    filenames: Sequence[str],
    timeout: float,
) -> dict[str, dict[str, Any]]:
    """Poll until every `filenames` entry has a `meta.ingestion_runs` row in a terminal status.

    Returns `{filename: {"status": ..., "run_id": ..., "schema_version_id": ..., "file_id": ...}}`.
    A single deadline loop over ALL filenames at once (not N separate per-file polls), matching
    this module's own scale (a handful of files, one discover call drains all of them together).

    `DISTINCT ON (f.filename) ... ORDER BY f.filename, ir.run_id DESC NULLS LAST` -- a file CAN
    have more than one `meta.ingestion_runs` row (a prior attempt that never reached a terminal
    status, e.g. an infra-outage-interrupted run left permanently `RUNNING` with no
    `finished_at`), and a plain `LEFT JOIN` with no ordering returns ALL of them, non-
    deterministically overwriting this function's per-filename dict in whatever order Postgres
    happens to return rows -- which could mean this loop keeps observing a stale, permanently-
    `RUNNING` OLD row forever even after a genuinely NEWER attempt reaches `SUCCEEDED` (live-
    discovered this session: see module docstring). Selecting the highest `run_id` per filename
    is the fix -- the latest attempt is always the one that matters.
    """
    deadline = time.monotonic() + timeout
    results: dict[str, dict[str, Any]] = {}
    while time.monotonic() < deadline:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT DISTINCT ON (f.filename)
                       f.filename, f.file_id, ir.status, ir.run_id, ir.schema_version_id
                  FROM meta.files f
                  JOIN meta.datasets d ON d.dataset_id = f.dataset_id
                  LEFT JOIN meta.ingestion_runs ir ON ir.file_id = f.file_id
                 WHERE d.dataset_name = %s AND f.filename = ANY(%s)
                 ORDER BY f.filename, ir.run_id DESC NULLS LAST
                """,
                (dataset, list(filenames)),
            )
            rows = cur.fetchall()
        for filename, file_id, status, run_id, schema_version_id in rows:
            results[filename] = {
                "file_id": file_id,
                "status": status,
                "run_id": run_id,
                "schema_version_id": schema_version_id,
            }
        if len(results) == len(filenames) and all(
            r["status"] in _TERMINAL_RUN_STATUSES for r in results.values()
        ):
            return results
        time.sleep(_POLL_INTERVAL_SECONDS)
    missing = sorted(set(filenames) - results.keys())
    pending = {
        k: v["status"] for k, v in results.items() if v["status"] not in _TERMINAL_RUN_STATUSES
    }
    msg = (
        f"dataset={dataset!r}: not all of {len(filenames)} filenames reached a terminal "
        f"meta.ingestion_runs status within {timeout}s -- missing entirely: {missing}, "
        f"still non-terminal: {pending}"
    )
    raise AssertionError(msg)


def _customer_rows_in_file(
    files: dict[str, bytes], filename: str, customer_id: int
) -> list[dict[str, str]]:
    """Every row in `files[filename]` for `customer_id`, in file order, as `{column: value}` dicts.

    A roster member can legitimately appear MORE than once in one file -- D-11's late-correction
    mechanic (`tools/corpus/dated_series.py`) appends an EXTRA row after the full roster resend,
    so this returns every match, in the SAME order they appear in the file; a caller needing a
    specific occurrence (e.g. the LAST one, the appended correction) indexes into the result
    itself. `sweep_corpus.customers_files` (module-scoped, generated once) is this corpus' own
    single source of truth for exactly what was injected -- reading it directly here means this
    module's own SCD assertions never need to re-derive an expected value via
    `tools.corpus.dated_series`'s private helper functions.
    """
    text = files[filename].decode("utf-8")
    lines = [line for line in text.split("\r\n") if line]
    header = lines[0].split(",")
    matches: list[dict[str, str]] = []
    for line in lines[1:]:
        fields = line.split(",")
        if fields[0] == str(customer_id):
            matches.append(dict(zip(header, fields, strict=True)))
    return matches


def _customer_version_counts(conn: psycopg.Connection[Any]) -> dict[int, int]:
    """`{customer_id: SCD2 version row count}` for every customer_id in `normalized.customers`.

    D-12 (plan 10-07 Task 2)'s own oracle: a full second backfill re-run over the identical
    window must produce a BYTE-FOR-BYTE identical snapshot of this mapping -- not merely an
    unchanged TOTAL row count (which cannot distinguish "zero net change" from "one customer_id
    lost a version while another gained one").
    """
    with conn.cursor() as cur:
        cur.execute("SELECT customer_id, count(*) FROM normalized.customers GROUP BY customer_id")
        rows = cur.fetchall()
    return {int(customer_id): int(count) for customer_id, count in rows}


def _customer_current_state_snapshot(
    conn: psycopg.Connection[Any], customer_ids: Sequence[int]
) -> dict[int, tuple[Any, int]]:
    """`{customer_id: (current version's own event_ts, TOTAL version-row count for that key)}`.

    D-06 (plan 10-07 Task 3)'s own pre/post gold-state oracle: a FAILED run (the mass-delete
    circuit breaker tripping) must leave every one of these values byte-for-byte unchanged --
    proving the breaker is a PRE-mutation barrier stage (D-06's own `BarrierStage` design), not
    a partial-apply-then-fail race. Scoped to `customer_ids` only -- this is a shared,
    cluster-wide table other live e2e suites also write to.
    """
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT customer_id, event_ts, count(*) OVER (PARTITION BY customer_id)
              FROM normalized.customers
             WHERE customer_id = ANY(%s) AND is_current
            """,
            (list(customer_ids),),
        )
        rows = cur.fetchall()
    return {
        int(customer_id): (event_ts, int(version_count))
        for customer_id, event_ts, version_count in rows
    }


def _table_row_count(conn: psycopg.Connection[Any], table: str) -> int:
    with conn.cursor() as cur:
        cur.execute(f"SELECT count(*) FROM {table}")  # noqa: S608 -- table is a fixed literal, never row content
        row = cur.fetchone()
    assert row is not None
    return int(row[0])


def _scoped_row_count(
    conn: psycopg.Connection[Any], table: str, id_column: str, lower: int, upper: int
) -> int:
    """Like `_table_row_count`, but scoped to `id_column IN [lower, upper)`.

    `table` is a shared, cluster-wide table other live e2e suites also write to (each with
    its own disjoint id range, per dated_series.py's module docstring) -- an unscoped count
    over-counts by however many rows those OTHER suites left behind.

    `id_column::bigint` -- live-discovered this session: `normalized.orders.order_id` is a
    real `integer` column, but `silver.orders.order_id` (the dbt-managed intermediate layer)
    is still `text`, matching STACK.md's own "business columns stay TEXT until the final
    gold-layer INSERT casts" convention. The explicit cast makes this helper correct against
    either shape; it is a no-op on the already-integer table.
    """
    with conn.cursor() as cur:
        cur.execute(
            f"SELECT count(*) FROM {table} "  # noqa: S608 -- table/id_column are fixed literals, never row content
            f"WHERE {id_column}::bigint >= %s AND {id_column}::bigint < %s",
            (lower, upper),
        )
        row = cur.fetchone()
    assert row is not None
    return int(row[0])


def _watermark_cursor_value(conn: psycopg.Connection[Any], *, dataset: str) -> datetime | None:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT w.cursor_value
              FROM meta.watermarks w
              JOIN meta.datasets d ON d.dataset_id = w.dataset_id
             WHERE d.dataset_name = %s AND w.target_key = 'default'
            """,
            (dataset,),
        )
        row = cur.fetchone()
    return None if row is None else row[0]


def _reconciliation_rows(
    conn: psycopg.Connection[Any], *, dataset: str, hop: str
) -> list[dict[str, Any]]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT rr.file_id, rr.input_count, rr.output_count, rr.rejected_count,
                   rr.dedup_count, rr.discrepancy
              FROM meta.reconciliation_results rr
              JOIN meta.datasets d ON d.dataset_id = rr.dataset_id
             WHERE d.dataset_name = %s AND rr.hop = %s
            """,
            (dataset, hop),
        )
        rows = cur.fetchall()
    return [
        {
            "file_id": r[0],
            "input_count": r[1],
            "output_count": r[2],
            "rejected_count": r[3],
            "dedup_count": r[4],
            "discrepancy": r[5],
        }
        for r in rows
    ]


def _failed_scheduling_event_snapshot(
    kubectl_json_fn: Callable[..., Any],
) -> dict[str, int]:
    """`{event_uid: count}` for every `FailedScheduling` event currently in the `etl` namespace.

    Kubernetes coalesces repeated identical events (bumping `count`/`lastTimestamp` on the SAME
    object) rather than creating new ones -- comparing `count` per UID before/after a window
    catches both a brand-new event AND a pre-existing one recurring, without over-counting stale
    history the pilot's own run never caused.
    """
    result = kubectl_json_fn(
        "-n", _ETL_NAMESPACE, "get", "events",
        "--field-selector=reason=FailedScheduling", "-o", "json",
    )
    return {item["metadata"]["uid"]: item.get("count", 1) for item in result.get("items", [])}


# ---------------------------------------------------------------------------
# Task 1: dry-run sizing + pilot window
# ---------------------------------------------------------------------------


def test_dry_run_sizing_reports_reasonable_dagrun_count(
    sweep_corpus: _Corpus,  # noqa: ARG001 -- ensures the corpus is uploaded before this dry-run
    kubectl: Callable[..., subprocess.CompletedProcess[str]],
) -> None:
    """Pitfall 1's exact guard: `--dry-run` reports tens of ticks, never hundreds of thousands."""
    from_dt, to_dt = _window(offset_minutes=600, span_minutes=5)
    tick_count = _dry_run_tick_count(
        kubectl,
        dag_id=_CUSTOMERS_DAG_ID,
        from_iso=from_dt.isoformat(),
        to_iso=to_dt.isoformat(),
    )
    assert tick_count == 6, (
        f"expected exactly 6 ticks for a 5-minute window (both endpoints inclusive), got "
        f"{tick_count}"
    )
    assert tick_count < 1000, (
        f"dry-run reported {tick_count} DagRuns for a {5}-minute window -- Pitfall 1's exact "
        f"failure mode (a literal multi-year window at 1-minute granularity enumerates hundreds "
        f"of thousands of DagRuns); the window choice itself, not just this assertion, must stay "
        f"minutes-sized, never years-sized"
    )


def test_pilot_window_drains_without_cpu_starvation(  # noqa: PLR0913, PLR0917 -- one param per
    # fixture this test genuinely needs (corpus, cross-test state, 2 kubectl variants, 2 DB conns)
    sweep_corpus: _Corpus,
    sweep_state: _SweepState,
    kubectl: Callable[..., subprocess.CompletedProcess[str]],
    kubectl_json: Callable[..., Any],
    analytics_connection: psycopg.Connection[Any],
    airflow_metadata_connection: psycopg.Connection[Any],
) -> None:
    """A short, real backfill pilot: no FailedScheduling starvation, at least one file processed.

    D-12's "try, then degrade": starts at `--max-active-runs 3`; if the live cluster shows a NEW
    or recurring `FailedScheduling: Insufficient cpu` event in the `etl` namespace during the
    pilot, `sweep_state.max_active_runs` degrades to `1` for Task 2/3 to reuse.
    """
    before = _failed_scheduling_event_snapshot(kubectl_json)

    from_dt, to_dt = _window(offset_minutes=500, span_minutes=1)
    since_id = _latest_backfill_id(airflow_metadata_connection, dag_id=_CUSTOMERS_DAG_ID)
    _invoke_backfill_create(
        kubectl,
        dag_id=_CUSTOMERS_DAG_ID,
        from_iso=from_dt.isoformat(),
        to_iso=to_dt.isoformat(),
        max_active_runs=sweep_state.max_active_runs,
    )

    # Poll for at least one customers file to have a real, terminal ingestion_runs row --
    # "confirm at least one file was discovered/staged" (Task 1's own acceptance criteria).
    first_filename = sweep_corpus.customers_manifest.filenames[0]
    results = _wait_for_dataset_files_terminal(
        analytics_connection,
        dataset=_CUSTOMERS_DATASET,
        filenames=[first_filename],
        timeout=600,
    )
    assert results[first_filename]["status"] == "SUCCEEDED", (
        f"pilot window's own file {first_filename!r} finished "
        f"{results[first_filename]['status']!r}, not SUCCEEDED"
    )

    # Airflow's own bookkeeping: the backfill itself reached completion.
    # Observed real cluster throughput: ~5-10 min per 2-tick pilot window under CPU contention.
    _wait_for_new_backfill_completed(
        airflow_metadata_connection,
        dag_id=_CUSTOMERS_DAG_ID,
        since_backfill_id=since_id,
        timeout=900,
    )

    after = _failed_scheduling_event_snapshot(kubectl_json)
    new_or_grown = {
        uid: (before.get(uid, 0), count)
        for uid, count in after.items()
        if count > before.get(uid, 0)
    }
    if new_or_grown:
        sweep_state.max_active_runs = 1
    assert sweep_state.max_active_runs in (1, 3), "sanity: only two values this test ever assigns"


# ---------------------------------------------------------------------------
# Task 2: full sweep -- both datasets, all correctness properties
# ---------------------------------------------------------------------------


def test_full_2year_sweep_customers_and_orders(  # noqa: PLR0915 -- 7 independently-named
    # correctness properties (D-05..D-11), each needing its own setup/query/assert; splitting
    # would scatter one coherent live proof across artificial fixtures for no reader benefit.
    sweep_corpus: _Corpus,
    sweep_state: _SweepState,
    kubectl: Callable[..., subprocess.CompletedProcess[str]],
    analytics_connection: psycopg.Connection[Any],
    airflow_metadata_connection: psycopg.Connection[Any],
) -> None:
    """The 7-assertion live proof (D-05..D-11), see module docstring for the 3 deviations.

    Runs a REAL `airflow backfill create` for `csv_ingest_customers` only (Deviation 1: orders
    cannot be targeted directly -- `DagNonPeriodicScheduleException`), waits for every generated
    file in BOTH datasets to reach a terminal `meta.ingestion_runs` status (orders drains via its
    own Asset-triggered cascade off customers' publish), then asserts all 7 correctness
    properties via direct SQL.
    """
    from_dt, to_dt = _window(offset_minutes=400, span_minutes=2)
    sweep_state.full_sweep_from = from_dt
    sweep_state.full_sweep_to = to_dt

    since_id = _latest_backfill_id(airflow_metadata_connection, dag_id=_CUSTOMERS_DAG_ID)
    _invoke_backfill_create(
        kubectl,
        dag_id=_CUSTOMERS_DAG_ID,
        from_iso=from_dt.isoformat(),
        to_iso=to_dt.isoformat(),
        max_active_runs=sweep_state.max_active_runs,
    )
    # Sizing: at max_active_runs=1 (fully sequential, no concurrent pod-scheduling pressure),
    # 3 sequential customers dag_runs at the observed ~20-25 min/run pace under this cluster's
    # CPU contention could take up to ~75 min total -- 5400s (90 min) budgets that with headroom.
    _wait_for_new_backfill_completed(
        airflow_metadata_connection,
        dag_id=_CUSTOMERS_DAG_ID,
        since_backfill_id=since_id,
        timeout=5400,
    )

    customers_manifest = sweep_corpus.customers_manifest
    orders_manifest = sweep_corpus.orders_manifest

    customers_results = _wait_for_dataset_files_terminal(
        analytics_connection,
        dataset=_CUSTOMERS_DATASET,
        filenames=customers_manifest.filenames,
        timeout=5400,
    )
    for filename, result in customers_results.items():
        assert result["status"] == "SUCCEEDED", (
            f"customers file {filename!r} finished {result['status']!r}, not SUCCEEDED"
        )

    # Deviation 1: orders drains via its OWN Asset-triggered cascade, never a direct backfill
    # CLI call -- poll for the SAME terminal-status guarantee regardless of trigger mechanism.
    # Sizing: at max_active_runs=1, orders' own 13-file drain only starts once customers' full
    # sequential 3-run backfill completes and fires the asset event, ON TOP OF its own
    # observed ~1-2 min/file serialized cadence under CPU contention -- 5400s (90 min) budgets
    # a full 13-file drain at that rate plus generous headroom (err generous rather than
    # re-guessing a tighter number again).
    orders_results = _wait_for_dataset_files_terminal(
        analytics_connection,
        dataset=_ORDERS_DATASET,
        filenames=orders_manifest.filenames,
        timeout=5400,
    )
    for filename, result in orders_results.items():
        assert result["status"] == "SUCCEEDED", (
            f"orders file {filename!r} finished {result['status']!r}, not SUCCEEDED"
        )

    expected_row_count = (_NUM_DAYS - 1) * _ROWS_PER_DAY  # gap day excluded, no dedup collisions

    # --- (1) silver.orders/normalized.orders non-empty, consistent with the corpus minus the gap
    #     day (D-08: closes the silver.orders 0-rows gap). ---
    # `normalized.orders`/`silver.orders` are shared, cluster-wide tables -- other live e2e
    # suites (e.g. test_referential_orphan.py, its own disjoint order_id range per
    # dated_series.py's module docstring) leave their own rows behind too, so an unscoped
    # `count(*)` over-counts (live-discovered this session: got 656 against an expected 650,
    # traced to exactly 6 rows outside this corpus' own order_id range). Scope both counts to
    # THIS corpus' own order_id space (`_ORDER_ID_BASE` .. `+ _NUM_DAYS * _ID_DAY_MULTIPLIER`,
    # generously wide -- `_ROWS_PER_DAY` rows/day never approaches the multiplier) so the
    # assertion reflects only what this run itself produced.
    order_id_upper_bound = _ORDER_ID_BASE + _NUM_DAYS * _ID_DAY_MULTIPLIER
    silver_orders_count = _scoped_row_count(
        analytics_connection, "silver.orders", "order_id", _ORDER_ID_BASE, order_id_upper_bound
    )
    normalized_orders_count = _scoped_row_count(
        analytics_connection,
        "normalized.orders",
        "order_id",
        _ORDER_ID_BASE,
        order_id_upper_bound,
    )
    assert silver_orders_count > 0, "silver.orders is empty -- D-08's 0-rows gap did not close"
    assert normalized_orders_count > 0, (
        "normalized.orders is empty -- D-08's 0-rows gap did not close"
    )
    assert normalized_orders_count == expected_row_count, (
        f"expected normalized.orders row count == {expected_row_count} "
        f"(({_NUM_DAYS} - 1 gap) * {_ROWS_PER_DAY} rows/day; this corpus' orders.customer_id "
        f"pool is drawn from customers' own day-0 range, so every row resolves referentially "
        f"clean, no quarantine expected), got {normalized_orders_count}"
    )

    # --- (2, adapted -- module docstring Deviation 3): the gap day is genuinely absent
    #     everywhere, every OTHER day was processed, and meta.processing_gaps correctly has
    #     ZERO rows for this whole-bucket-populated corpus (its real, live-confirmed semantics
    #     is "the whole listing was empty", not "one day is missing among many present"). ---
    gap_day = _START_DATE + timedelta(days=_GAP_DAY_INDEX)
    gap_filename = f"customers_{gap_day.strftime('%Y%m%d')}.csv"
    assert gap_filename not in customers_results, (
        f"the gap day's file {gap_filename!r} unexpectedly has a meta.ingestion_runs row -- it "
        f"was never uploaded and must never be discovered"
    )
    assert len(customers_results) == len(customers_manifest.filenames) == _NUM_DAYS - 1, (
        "expected every non-gap day's file to be discovered and reach a terminal status -- the "
        "gap must not stop the rest of the window"
    )
    gap_rows = _table_row_count(analytics_connection, "meta.processing_gaps")
    assert gap_rows == 0, (
        f"meta.processing_gaps has {gap_rows} row(s), expected 0: this corpus keeps "
        f"{len(customers_manifest.filenames)} real files permanently in the bucket, so "
        f"list_matched_keys (bucket-wide, date-agnostic) is never empty for any tick -- "
        f"record_processing_gap_if_empty's real, live-confirmed semantics only fire on a "
        f"WHOLE-LISTING-EMPTY tick, not a single missing day among many present ones (module "
        f"docstring Deviation 3) -- 0 is the CORRECT value here, not a bug"
    )

    # --- (3) pre-schema-change files resolve under their OWN historical schema version,
    #     differing from post-schema-change runs' version (D-07). ---
    pre_change_day = _START_DATE  # day_index=0, always < schema_change_day_index
    pre_change_filename = f"customers_{pre_change_day.strftime('%Y%m%d')}.csv"
    post_change_day = _START_DATE + timedelta(days=_SCHEMA_CHANGE_DAY_INDEX)
    post_change_filename = f"customers_{post_change_day.strftime('%Y%m%d')}.csv"
    pre_schema_version_id = customers_results[pre_change_filename]["schema_version_id"]
    post_schema_version_id = customers_results[post_change_filename]["schema_version_id"]
    assert pre_schema_version_id is not None, f"{pre_change_filename!r} has no schema_version_id"
    assert post_schema_version_id is not None, f"{post_change_filename!r} has no schema_version_id"
    assert pre_schema_version_id != post_schema_version_id, (
        f"pre-schema-change file {pre_change_filename!r} (schema_version_id="
        f"{pre_schema_version_id!r}) and post-schema-change file {post_change_filename!r} "
        f"(schema_version_id={post_schema_version_id!r}) resolved under the SAME schema "
        f"version -- D-07's historical-schema-resolution proof requires them to differ"
    )

    # --- (4) the late/out-of-order record lands correctly ordered by BUSINESS timestamp, not
    #     arrival order (D-05); every row's business key is globally unique in this corpus (no
    #     dedup collision is even possible), so the proof is that the late row's OWN event_ts in
    #     normalized.customers matches its BACKDATED value verbatim -- never silently corrected
    #     forward to its file's nominal day. ---
    late_day = _START_DATE + timedelta(days=_LATE_EVENT_DAY_INDEX)
    late_filename = f"customers_{late_day.strftime('%Y%m%d')}.csv"
    late_run_id = customers_results[late_filename]["run_id"]
    with analytics_connection.cursor() as cur:
        cur.execute(
            "SELECT customer_id FROM silver.customers WHERE _run_id = %s "
            "ORDER BY event_ts ASC LIMIT 1",
            (late_run_id,),
        )
        late_silver_row = cur.fetchone()
    assert late_silver_row is not None, f"silver.customers has no rows for _run_id={late_run_id!r}"
    late_customer_id = int(late_silver_row[0])
    expected_late_event_ts = datetime(
        late_day.year, late_day.month, late_day.day, 8, 15, 0, tzinfo=UTC
    ) - timedelta(days=_LATE_EVENT_OFFSET_DAYS)
    with analytics_connection.cursor() as cur:
        cur.execute(
            "SELECT event_ts FROM normalized.customers WHERE customer_id = %s",
            (late_customer_id,),
        )
        late_gold_row = cur.fetchone()
    assert late_gold_row is not None, f"late customer_id={late_customer_id!r} never published"
    assert late_gold_row[0] == expected_late_event_ts, (
        f"expected the late row's (customer_id={late_customer_id!r}) own event_ts to be its "
        f"backdated value {expected_late_event_ts!r} (never silently corrected to the file's "
        f"nominal day {late_day!r}), got {late_gold_row[0]!r}"
    )

    # --- (5) meta.watermarks.cursor_value equals the TRUE max event_ts/order_date across the
    #     whole corpus -- never the late event's earlier value, never simply "today" (INCR-01/
    #     02's live proof). ---
    last_day = _START_DATE + timedelta(days=_NUM_DAYS - 1)
    expected_customers_watermark = datetime(
        last_day.year, last_day.month, last_day.day, 8, 15, 0, tzinfo=UTC
    )
    customers_watermark = _watermark_cursor_value(analytics_connection, dataset=_CUSTOMERS_DATASET)
    assert customers_watermark == expected_customers_watermark, (
        f"expected meta.watermarks.cursor_value for customers == "
        f"{expected_customers_watermark!r} (the corpus' own true last day -- never the late "
        f"event's backdated {expected_late_event_ts!r} value, never simply 'today'), got "
        f"{customers_watermark!r}"
    )
    expected_orders_watermark = datetime(
        last_day.year, last_day.month, last_day.day, tzinfo=UTC
    )
    orders_watermark = _watermark_cursor_value(analytics_connection, dataset=_ORDERS_DATASET)
    assert orders_watermark == expected_orders_watermark, (
        f"expected meta.watermarks.cursor_value for orders == {expected_orders_watermark!r}, "
        f"got {orders_watermark!r}"
    )

    # --- (6) meta.reconciliation_results has rows for all 3 hops for every processed file, with
    #     D-22's own accounting formula holding exactly. ---
    for dataset, manifest in (
        (_CUSTOMERS_DATASET, customers_manifest),
        (_ORDERS_DATASET, orders_manifest),
    ):
        for hop in ("raw_bronze", "bronze_silver", "silver_gold"):
            rows = _reconciliation_rows(analytics_connection, dataset=dataset, hop=hop)
            assert rows, (
                f"meta.reconciliation_results has zero rows for dataset={dataset!r} hop={hop!r}"
            )
            observed_file_ids = {row["file_id"] for row in rows}
            source_results = customers_results if dataset == _CUSTOMERS_DATASET else orders_results
            expected_file_ids = {source_results[f]["file_id"] for f in manifest.filenames}
            assert expected_file_ids <= observed_file_ids, (
                f"dataset={dataset!r} hop={hop!r}: expected reconciliation rows for every "
                f"processed file_id, missing {expected_file_ids - observed_file_ids!r}"
            )
            for row in rows:
                if row["file_id"] not in expected_file_ids:
                    continue  # a row from an earlier plan's own live-proof run, not this sweep's
                assert row["discrepancy"] == row["input_count"] - (
                    row["output_count"] + row["rejected_count"] + row["dedup_count"]
                ), (
                    f"D-22's own accounting formula does not hold for dataset={dataset!r} "
                    f"hop={hop!r} file_id={row['file_id']!r}: {row!r}"
                )

    # --- (7) a normal live-scheduled DagRun (backfill_id IS NULL) ALSO succeeds through the
    #     identical task graph, no special-casing (D-11). Orders is Asset-triggered
    #     (Deviation 1): EVERY orders DagRun this sweep produced is inherently backfill_id IS
    #     NULL, which is itself the proof -- orders never even has a "backfill mode" to special-
    #     case, because it always runs through the ONE structure it has. ---
    with airflow_metadata_connection.cursor() as cur:
        cur.execute(
            "SELECT count(*) FROM dag_run "
            "WHERE dag_id = %s AND backfill_id IS NULL AND state = 'success'",
            (_ORDERS_DAG_ID,),
        )
        orders_live_success_row = cur.fetchone()
    assert orders_live_success_row is not None
    orders_live_success_count = orders_live_success_row[0]
    assert orders_live_success_count > 0, (
        "expected at least one csv_ingest_orders DagRun with backfill_id IS NULL to reach "
        "'success' -- orders is Asset-triggered (module docstring Deviation 1), so this "
        "confirms it processed this sweep's files through the SAME task graph a live trigger "
        "would use, with no bypass or special-casing by temporal mode"
    )

    # =========================================================================
    # Plan 10-07 Task 1: D-11's three SCD anomalies, live against the real
    # cluster (SCD-01/02/03/06/07/08).
    # =========================================================================

    # --- (8) the attribute-change member shows exactly 2 correctly-bracketed
    #     SCD2 version rows: pre-change baseline, then the permanently-
    #     changed value from the change day onward, is_current only on the
    #     later row (SCD-01/02's Type-2 dispatch, proven live). ---
    attribute_change_customer_id = _CUSTOMER_ID_BASE + _ATTRIBUTE_CHANGE_MEMBER_INDEX
    change_day = _START_DATE + timedelta(days=_ATTRIBUTE_CHANGE_DAY_INDEX)
    expected_change_ts = datetime(
        change_day.year, change_day.month, change_day.day, 8, 15, 0, tzinfo=UTC
    )
    attribute_change_baseline_filename = f"customers_{_START_DATE.strftime('%Y%m%d')}.csv"
    attribute_change_changed_filename = f"customers_{change_day.strftime('%Y%m%d')}.csv"
    attribute_change_baseline_row = _customer_rows_in_file(
        sweep_corpus.customers_files,
        attribute_change_baseline_filename,
        attribute_change_customer_id,
    )[0]
    attribute_change_changed_row = _customer_rows_in_file(
        sweep_corpus.customers_files,
        attribute_change_changed_filename,
        attribute_change_customer_id,
    )[0]
    assert (
        attribute_change_baseline_row["name"] != attribute_change_changed_row["name"]
        or attribute_change_baseline_row["country"] != attribute_change_changed_row["country"]
    ), (
        f"attribute-change fixture is not actually different from baseline for customer_id="
        f"{attribute_change_customer_id!r} -- generator/day-index setup is broken"
    )
    with analytics_connection.cursor() as cur:
        cur.execute(
            "SELECT event_ts, valid_to, is_current, name, country FROM normalized.customers "
            "WHERE customer_id = %s ORDER BY event_ts",
            (attribute_change_customer_id,),
        )
        attribute_change_versions = cur.fetchall()
    assert len(attribute_change_versions) == 2, (
        f"expected exactly 2 SCD2 version rows for the attribute-change member "
        f"(customer_id={attribute_change_customer_id!r}), proving SCD-01/02's Type-2 dispatch "
        f"collapses every unchanged daily resend into ONE version and opens exactly one more on "
        f"the change day -- got {len(attribute_change_versions)}: {attribute_change_versions!r}"
    )
    (_v1_from, v1_to, v1_current, v1_name, v1_country) = attribute_change_versions[0]
    (v2_from, _v2_to, v2_current, v2_name, v2_country) = attribute_change_versions[1]
    assert v1_to == expected_change_ts, (
        f"expected the pre-change version's valid_to to equal the change day's own event_ts "
        f"{expected_change_ts!r} (correctly bracketing the change day's date), got {v1_to!r}"
    )
    assert v2_from == expected_change_ts, (
        f"expected the post-change version's event_ts (valid_from) to equal the change day's "
        f"own event_ts {expected_change_ts!r}, got {v2_from!r}"
    )
    assert v1_current is False, (
        f"expected the pre-change version to NOT be is_current, got is_current={v1_current!r}"
    )
    assert v2_current is True, (
        f"expected the post-change (later) version to be is_current, got is_current={v2_current!r}"
    )
    assert (v1_name, v1_country) == (
        attribute_change_baseline_row["name"],
        attribute_change_baseline_row["country"],
    ), (
        f"pre-change version's (name, country) does not match the corpus' own baseline row: "
        f"got {(v1_name, v1_country)!r}, expected "
        f"{(attribute_change_baseline_row['name'], attribute_change_baseline_row['country'])!r}"
    )
    assert (v2_name, v2_country) == (
        attribute_change_changed_row["name"],
        attribute_change_changed_row["country"],
    ), (
        f"post-change version's (name, country) does not match the corpus' own changed row: "
        f"got {(v2_name, v2_country)!r}, expected "
        f"{(attribute_change_changed_row['name'], attribute_change_changed_row['country'])!r}"
    )

    # --- (9) the late-correction member (SCD-07) shows the backdated
    #     correction slotted chronologically INSIDE the version chain, not
    #     appended at the end: 3 versions (baseline, the backdated
    #     correction, baseline resumed), the correction's own event_ts
    #     (valid_from) strictly between the OTHER two versions' own
    #     event_ts boundaries -- proving recompute REPOSITIONS a late
    #     correction chronologically. ---
    late_correction_customer_id = _CUSTOMER_ID_BASE + _LATE_CORRECTION_MEMBER_INDEX
    correction_arrival_day = _START_DATE + timedelta(days=_LATE_CORRECTION_ARRIVAL_DAY_INDEX)
    correction_arrival_filename = f"customers_{correction_arrival_day.strftime('%Y%m%d')}.csv"
    correction_matches = _customer_rows_in_file(
        sweep_corpus.customers_files, correction_arrival_filename, late_correction_customer_id
    )
    assert len(correction_matches) == 2, (
        f"expected exactly 2 occurrences of customer_id={late_correction_customer_id!r} in "
        f"{correction_arrival_filename!r} (the normal roster resend row, then the EXTRA "
        f"backdated correction row appended after it) -- got {len(correction_matches)}"
    )
    correction_row = correction_matches[-1]  # the LAST occurrence is the appended correction
    with analytics_connection.cursor() as cur:
        cur.execute(
            "SELECT event_ts, valid_to, is_current, name, country FROM normalized.customers "
            "WHERE customer_id = %s ORDER BY event_ts",
            (late_correction_customer_id,),
        )
        late_correction_versions = cur.fetchall()
    assert len(late_correction_versions) == 3, (
        f"expected exactly 3 SCD2 version rows for the late-correction member "
        f"(customer_id={late_correction_customer_id!r}) -- baseline, the backdated correction, "
        f"then baseline resumed -- got {len(late_correction_versions)}: "
        f"{late_correction_versions!r}"
    )
    (prior_from, _prior_to, prior_current, _prior_name, _prior_country) = late_correction_versions[
        0
    ]
    (
        correction_from,
        _correction_to,
        correction_current,
        correction_name,
        correction_country,
    ) = late_correction_versions[1]
    (later_from, _later_to, later_current, _later_name, _later_country) = late_correction_versions[
        2
    ]
    assert prior_from < correction_from < later_from, (
        f"expected the correction's own event_ts (valid_from={correction_from!r}) to fall "
        f"STRICTLY between the prior version's event_ts ({prior_from!r}) and the later "
        f"version's event_ts ({later_from!r}) -- SCD-07's chronological repositioning, not a "
        f"mere append at the end"
    )
    assert (correction_name, correction_country) == (
        correction_row["name"],
        correction_row["country"],
    ), (
        f"the middle (correction) version's (name, country) does not match the corpus' own "
        f"backdated correction row: got {(correction_name, correction_country)!r}, expected "
        f"{(correction_row['name'], correction_row['country'])!r}"
    )
    assert prior_current is False, (
        f"expected the prior (oldest) version to NOT be is_current, got "
        f"is_current={prior_current!r}"
    )
    assert correction_current is False, (
        f"expected the correction's own middle version to NEVER be is_current -- it is a "
        f"historical, already-superseded observation, not the latest state, got "
        f"is_current={correction_current!r}"
    )
    assert later_current is True, (
        f"expected the later (resumed-baseline) version to be is_current, got "
        f"is_current={later_current!r}"
    )

    # --- (10) the missing-customer member is correctly invalidated on the
    #     FINAL day's own pass: is_current=false, valid_to equal to the
    #     corpus' own last-observed max event_ts for that snapshot -- never
    #     a value close to wall-clock "now" (SCD-06 applied to the DELETE
    #     path), proving D-05's `invalidate` default fired correctly on a
    #     real cluster. ---
    missing_customer_id = _CUSTOMER_ID_BASE + _MISSING_CUSTOMER_MEMBER_INDEX
    with analytics_connection.cursor() as cur:
        cur.execute(
            "SELECT is_current, valid_to FROM normalized.customers WHERE customer_id = %s "
            "ORDER BY event_ts DESC LIMIT 1",
            (missing_customer_id,),
        )
        missing_customer_row = cur.fetchone()
    assert missing_customer_row is not None, (
        f"expected at least one normalized.customers row for the missing-customer member "
        f"(customer_id={missing_customer_id!r}) -- it was present every day except the last"
    )
    missing_is_current, missing_valid_to = missing_customer_row
    assert missing_is_current is False, (
        f"expected the missing-customer member's (customer_id={missing_customer_id!r}) latest "
        f"version to be closed (is_current=false) after D-05's `invalidate` semantics fired on "
        f"the final day's own pass -- proving the SCD Publisher's DELETE-detection (Step A) "
        f"correctly closed a customer absent from the corpus' own LAST snapshot, got "
        f"is_current={missing_is_current!r}"
    )
    assert missing_valid_to == expected_customers_watermark, (
        f"expected the missing-customer member's closed valid_to to equal the corpus' own "
        f"last-observed max event_ts {expected_customers_watermark!r} (SCD-06's effective-dating "
        f"requirement applied to the DELETE path -- an event-time-derived value, NEVER "
        f"wall-clock 'now'), got {missing_valid_to!r}"
    )


# ---------------------------------------------------------------------------
# Task 3: idempotency re-run + live+backfill concurrency proof
# ---------------------------------------------------------------------------


def test_idempotent_rerun_produces_zero_additional_rows(
    sweep_corpus: _Corpus,  # noqa: ARG001 -- ensures the corpus fixture (and its upload) stays alive
    sweep_state: _SweepState,
    kubectl: Callable[..., subprocess.CompletedProcess[str]],
    analytics_connection: psycopg.Connection[Any],
    airflow_metadata_connection: psycopg.Connection[Any],
) -> None:
    """QUAL-11: re-invoking the IDENTICAL backfill window produces zero additional rows.

    Pitfall 3: a re-triggered DagRun finding zero new work IS success, not failure --
    `discover_files`' own idempotency-key check means almost every re-triggered tick simply
    no-ops. This test's own row-count/watermark before/after comparison is designed around that
    expected outcome, not around "N discover units returned".
    """
    assert sweep_state.full_sweep_from is not None
    assert sweep_state.full_sweep_to is not None, (
        "sweep_state.full_sweep_to is unset -- test_full_2year_sweep_customers_and_orders must "
        "run first in this module (pytest's default in-file collection order)"
    )

    before_customers_count = _table_row_count(analytics_connection, "normalized.customers")
    before_orders_count = _table_row_count(analytics_connection, "normalized.orders")
    # D-12 (plan 10-07 Task 2): SCD2 version-COUNT-per-key snapshot, extending Phase 4's
    # original "re-run produces zero additional rows" pattern to version count -- a full
    # second backfill re-run must never mint an extra SCD2 version for any customer_id, not
    # merely leave the table's TOTAL row count unchanged (which the pre-existing
    # `before/after_customers_count` comparison below already checks, redundantly catching
    # any accidental extra INSERT this per-key snapshot might itself miss).
    before_customers_version_counts = _customer_version_counts(analytics_connection)
    before_customers_watermark = _watermark_cursor_value(
        analytics_connection, dataset=_CUSTOMERS_DATASET
    )
    before_orders_watermark = _watermark_cursor_value(analytics_connection, dataset=_ORDERS_DATASET)

    since_customers_backfill_id = _latest_backfill_id(
        airflow_metadata_connection, dag_id=_CUSTOMERS_DAG_ID
    )
    since_orders_dag_run_pk = _latest_dag_run_pk(airflow_metadata_connection, dag_id=_ORDERS_DAG_ID)

    _invoke_backfill_create(
        kubectl,
        dag_id=_CUSTOMERS_DAG_ID,
        from_iso=sweep_state.full_sweep_from.isoformat(),
        to_iso=sweep_state.full_sweep_to.isoformat(),
        max_active_runs=sweep_state.max_active_runs,
    )
    # Sizing: live-observed this session (Task 2's own retries and this test's own first
    # attempt), a re-triggered no-op dagrun still pays the FULL per-file KPO pod-startup cost
    # (~10-30s per mapped `integrity_gate`/`stage` pod x up to 18 files) -- "zero new rows" does
    # NOT mean "fast", since idempotency is checked INSIDE `discover`, after the pods already
    # spun up. A 3-dagrun re-run window under this cluster's real CPU contention (load average
    # 5-6 on 12 cores, observed live) took >900s for even the LAST of 3 dagruns alone -- 3600s
    # (60 min) budgets the whole window with real headroom, mirroring Task 2's own
    # generous-not-guessed-tight timeout philosophy.
    _wait_for_new_backfill_completed(
        airflow_metadata_connection,
        dag_id=_CUSTOMERS_DAG_ID,
        since_backfill_id=since_customers_backfill_id,
        timeout=3600,
    )
    # customers' `publish` task fires its `customers_asset` outlet on every SUCCEEDED run --
    # including a pure no-op re-run (finalize_publication handles an empty staged set the same
    # way) -- so orders' own Asset-triggered cascade re-fires too; wait for ITS re-execution to
    # settle before comparing final counts, rather than a blind sleep. 1800s (30 min): orders'
    # own re-run pays the same per-file pod-startup cost as customers' above, plus its dbt_build
    # step, under the same observed cluster contention.
    _wait_for_new_dag_run_terminal(
        airflow_metadata_connection,
        dag_id=_ORDERS_DAG_ID,
        since_pk=since_orders_dag_run_pk,
        timeout=1800,
    )

    after_customers_count = _table_row_count(analytics_connection, "normalized.customers")
    after_orders_count = _table_row_count(analytics_connection, "normalized.orders")
    after_customers_version_counts = _customer_version_counts(analytics_connection)
    after_customers_watermark = _watermark_cursor_value(
        analytics_connection, dataset=_CUSTOMERS_DATASET
    )
    after_orders_watermark = _watermark_cursor_value(analytics_connection, dataset=_ORDERS_DATASET)

    assert after_customers_count == before_customers_count, (
        f"expected normalized.customers TOTAL row count unchanged by the identical re-run, "
        f"before={before_customers_count} after={after_customers_count}"
    )
    changed_version_counts = {
        customer_id: (before_customers_version_counts.get(customer_id), version_count)
        for customer_id, version_count in after_customers_version_counts.items()
        if before_customers_version_counts.get(customer_id) != version_count
    }
    assert after_customers_version_counts == before_customers_version_counts, (
        f"expected the SCD2 version-count-per-customer_id snapshot to be BYTE-FOR-BYTE "
        f"identical after the identical re-run (D-12: re-running the entire backfill a "
        f"second time leaves the SCD2 version count for every customer_id unchanged) -- "
        f"changed (customer_id: (before, after)): {changed_version_counts!r}"
    )
    assert after_orders_count == before_orders_count, (
        f"expected normalized.orders row count unchanged by the identical re-run, "
        f"before={before_orders_count} after={after_orders_count}"
    )
    assert after_customers_watermark == before_customers_watermark, (
        f"expected meta.watermarks.cursor_value for customers unchanged by the identical "
        f"re-run (INCR-02's '>=, never >' rule holding), before={before_customers_watermark!r} "
        f"after={after_customers_watermark!r}"
    )
    assert after_orders_watermark == before_orders_watermark, (
        f"expected meta.watermarks.cursor_value for orders unchanged by the identical re-run, "
        f"before={before_orders_watermark!r} after={after_orders_watermark!r}"
    )


def test_live_run_concurrent_with_backfill_same_dataset(
    sweep_corpus: _Corpus,  # noqa: ARG001 -- ensures the corpus fixture stays alive
    sweep_state: _SweepState,
    kubectl: Callable[..., subprocess.CompletedProcess[str]],
    analytics_connection: psycopg.Connection[Any],
    airflow_metadata_connection: psycopg.Connection[Any],
) -> None:
    """D-12/D-13: a live customers DagRun runs CONCURRENTLY with an active backfill, no corruption.

    `csv_ingest_customers` stays unpaused for this whole module (session-scoped, autouse
    `_unpause_slice_dags` fixture, `tests/e2e/slice/conftest.py`) and every uploaded file
    permanently matches its `wait_for_files` sensor, so the DAG's own `*/1 * * * *` live schedule
    keeps producing ordinary `backfill_id IS NULL` DagRuns throughout this whole module's
    execution -- this test triggers a FRESH backfill window and polls for a live DagRun to be
    'running' at the SAME sampled instant, rather than assuming architecture guarantees it.
    """
    from_dt, to_dt = _window(offset_minutes=300, span_minutes=2)
    since_id = _latest_backfill_id(airflow_metadata_connection, dag_id=_CUSTOMERS_DAG_ID)
    _invoke_backfill_create(
        kubectl,
        dag_id=_CUSTOMERS_DAG_ID,
        from_iso=from_dt.isoformat(),
        to_iso=to_dt.isoformat(),
        max_active_runs=sweep_state.max_active_runs,
    )

    observed_concurrent = False
    # 600s (10 min): customers' live `*/1 * * * *` schedule normally creates a new DagRun within
    # a minute, but under this cluster's real CPU contention (observed live this session) task
    # pod scheduling can queue for several minutes before a task instance actually starts
    # running -- generous headroom over the architecturally-expected ~1 min.
    poll_deadline = time.monotonic() + 600
    while time.monotonic() < poll_deadline:
        with airflow_metadata_connection.cursor() as cur:
            cur.execute(
                """
                SELECT (backfill_id IS NULL) AS is_live, count(*)
                  FROM dag_run
                 WHERE dag_id = %s AND state = 'running'
                 GROUP BY backfill_id IS NULL
                """,
                (_CUSTOMERS_DAG_ID,),
            )
            counts = dict(cur.fetchall())
        if counts.get(True, 0) > 0 and counts.get(False, 0) > 0:
            observed_concurrent = True
            break
        time.sleep(_POLL_INTERVAL_SECONDS)

    # Sizing: same live-observed per-dagrun pace as test_idempotent_rerun's own comment above
    # (KPO pod-startup cost dominates, not row count) -- 2700s (45 min) for this single-window
    # backfill under this cluster's real CPU contention, with headroom.
    _wait_for_new_backfill_completed(
        airflow_metadata_connection,
        dag_id=_CUSTOMERS_DAG_ID,
        since_backfill_id=since_id,
        timeout=2700,
    )

    assert observed_concurrent, (
        "never observed a customers DagRun with backfill_id IS NOT NULL and a customers DagRun "
        "with backfill_id IS NULL BOTH state='running' at the same sampled instant within 300s "
        "-- D-13's live+backfill concurrency proof requires this overlap to actually occur, not "
        "just be architecturally possible"
    )

    # No corruption -- rewritten (plan 10-07 Task 2, RESEARCH.md Pattern 4): migration 0035
    # (plan 10-01) replaced normalized.customers's UNIQUE(customer_id) constraint with an
    # EXCLUDE USING gist constraint over (customer_id, validity) -- MULTIPLE rows per
    # customer_id are now the expected, correct SCD2 shape (this whole sweep's own Task 1
    # assertions prove customers legitimately carrying 2-3 version rows), so the ORIGINAL
    # "any duplicate customer_id row" check would misclassify every one of those as
    # corruption. The real SCD2 invariant under concurrent writes is TWO-FOLD: (a) at most
    # ONE is_current row per key, and (b) no two version rows for the same key ever have
    # overlapping validity ranges. Both are checked live here -- the exclusion constraint
    # SHOULD make (b) structurally impossible (RESEARCH.md's own "should never actually
    # fire" framing), but this test proves it holds under REAL concurrency, not merely via
    # the DDL's own guarantee.
    with analytics_connection.cursor() as cur:
        cur.execute(
            """
            SELECT customer_id, count(*)
              FROM normalized.customers
             WHERE is_current
             GROUP BY customer_id
            HAVING count(*) > 1
             LIMIT 5
            """
        )
        multiple_current = cur.fetchall()
    assert not multiple_current, (
        f"found customer_id(s) with MORE THAN ONE is_current=true row in "
        f"normalized.customers (genuine SCD2 corruption -- at most one current version per "
        f"key is required): {multiple_current!r}"
    )
    with analytics_connection.cursor() as cur:
        cur.execute(
            """
            SELECT a.customer_id
              FROM normalized.customers a
              JOIN normalized.customers b
                ON a.customer_id = b.customer_id
               AND a.id <> b.id
               AND a.validity && b.validity
             LIMIT 5
            """
        )
        overlapping_validity = cur.fetchall()
    assert not overlapping_validity, (
        f"found customer_id(s) with OVERLAPPING validity ranges in normalized.customers -- "
        f"the excl_customers_business_key_validity exclusion constraint (migration 0035) "
        f"should make this structurally impossible; a live occurrence would be genuine "
        f"corruption under concurrent writes: {overlapping_validity!r}"
    )


# ---------------------------------------------------------------------------
# Plan 10-07 Task 3: D-06's mass-delete circuit-breaker live trip proof
# ---------------------------------------------------------------------------


def test_mass_delete_snapshot_trips_circuit_breaker_without_mutating_gold_state(  # noqa: PLR0913, PLR0917
    # one param per fixture this test genuinely needs (corpus ordering, cross-test state,
    # kubectl, s3, 2 DB conns) -- mirrors test_pilot_window_drains_without_cpu_starvation's own
    # precedent for this exact lint exception, elsewhere in this module.
    sweep_corpus: _Corpus,  # noqa: ARG001 -- ensures test_full_2year_sweep's own gold state exists first
    sweep_state: _SweepState,
    kubectl: Callable[..., subprocess.CompletedProcess[str]],
    s3_client: Callable[[str], Any],
    analytics_connection: psycopg.Connection[Any],
    airflow_metadata_connection: psycopg.Connection[Any],
) -> None:
    """D-06: a real, deliberately-truncated customers snapshot trips the mass-delete circuit
    breaker against the real cluster -- the run fails LOUDLY (a hard `FAILED` terminal status,
    never a silent partial success, never merely `SKIPPED_DUPLICATE`) and gold state for every
    removed roster member is left byte-for-byte UNCHANGED, proving `MassDeleteCircuitBreaker`
    (plan 10-03) is a pre-mutation barrier stage, not a partial-apply-then-fail race.

    Runs AFTER `test_full_2year_sweep_customers_and_orders` has established real, current SCD2
    gold state for the sweep's roster (this file's own Task-ordering convention: pytest's
    default in-file collection order, mirroring every other test in this module).

    Generates ONE additional, single-day customers file via a SEPARATE `generate_dated_series`
    call -- same `master_seed`/`rows_per_day` as `sweep_corpus`'s own call (so the roster's
    customer_ids and baseline attribute values are IDENTICAL to what the main sweep already
    published; roster baselines are customer-scoped, not day-scoped, per plan 10-06 Task 1),
    `start_date` set to the day immediately following the extended sweep's own last day, so this
    fixture sits OUTSIDE the successful sweep's own window (tripping the breaker is expected to
    fail this one day's run loudly, not blend into the successful sweep). Triggers a single
    fresh customers DagRun for this one file (mirroring
    `test_live_run_concurrent_with_backfill_same_dataset`'s own "trigger one fresh DagRun
    outside the main window and poll" pattern, NOT `test_full_2year_sweep_customers_and_orders`'s
    whole-window backfill CLI usage), then polls `_wait_for_dataset_files_terminal` for it.
    """
    mass_delete_start_date = _START_DATE + timedelta(days=_NUM_DAYS)
    mass_delete_files, mass_delete_manifest = generate_dated_series(
        "customers",
        master_seed=_MASTER_SEED,
        start_date=mass_delete_start_date,
        num_days=1,
        # Required parameters, irrelevant here (single-day range, never reached).
        gap_day_index=1,
        schema_change_day_index=1,
        late_event_day_index=1,
        rows_per_day=_ROWS_PER_DAY,
        mass_delete_day_index=0,
        mass_delete_member_indices=_MASS_DELETE_MEMBER_INDICES,
    )
    assert len(mass_delete_manifest.filenames) == 1, (
        f"expected exactly 1 generated filename for this single-day fixture, got "
        f"{mass_delete_manifest.filenames!r}"
    )
    (mass_delete_filename,) = mass_delete_manifest.filenames

    removed_customer_ids = [_CUSTOMER_ID_BASE + m for m in _MASS_DELETE_MEMBER_INDICES]
    removed_fraction = len(_MASS_DELETE_MEMBER_INDICES) / _ROWS_PER_DAY
    assert removed_fraction > 0.10, (
        f"this fixture's removed fraction ({removed_fraction:.0%}) must comfortably exceed "
        f"customers.yaml's configured mass_delete_threshold (0.10) -- got {removed_fraction:.0%}"
    )

    before_snapshot = _customer_current_state_snapshot(analytics_connection, removed_customer_ids)
    assert len(before_snapshot) == len(removed_customer_ids), (
        f"expected a pre-existing is_current row for every removed member BEFORE this fixture "
        f"is even uploaded (established by test_full_2year_sweep_customers_and_orders) -- "
        f"got {len(before_snapshot)} of {len(removed_customer_ids)}: {before_snapshot!r}"
    )

    app = s3_client("app")
    app.put_object(
        Bucket="raw",
        Key=f"customers/{mass_delete_filename}",
        Body=mass_delete_files[mass_delete_filename],
    )

    # A SEPARATE, small window OUTSIDE test_full_2year_sweep's own window -- mirroring
    # test_live_run_concurrent_with_backfill_same_dataset's own "one fresh DagRun" pattern.
    # span_minutes=0 -- exactly one tick (verified live elsewhere in this module: a window's
    # tick count is inclusive on both ends).
    from_dt, to_dt = _window(offset_minutes=150, span_minutes=0)
    since_id = _latest_backfill_id(airflow_metadata_connection, dag_id=_CUSTOMERS_DAG_ID)
    _invoke_backfill_create(
        kubectl,
        dag_id=_CUSTOMERS_DAG_ID,
        from_iso=from_dt.isoformat(),
        to_iso=to_dt.isoformat(),
        max_active_runs=sweep_state.max_active_runs,
    )
    # Sizing: a single-file DagRun -- one integrity_gate/stage/dbt_build/publish pod chain, not
    # a multi-file sweep -- but under this cluster's documented CPU contention, budget the same
    # generous headroom this module's own other single-window tests use.
    _wait_for_new_backfill_completed(
        airflow_metadata_connection,
        dag_id=_CUSTOMERS_DAG_ID,
        since_backfill_id=since_id,
        timeout=1800,
    )

    results = _wait_for_dataset_files_terminal(
        analytics_connection,
        dataset=_CUSTOMERS_DATASET,
        filenames=[mass_delete_filename],
        timeout=1800,
    )
    assert results[mass_delete_filename]["status"] == "FAILED", (
        f"expected the deliberately-truncated snapshot's terminal meta.ingestion_runs.status "
        f"to be exactly 'FAILED' (the mass-delete circuit breaker raised "
        f"QualityThresholdExceeded inside the SCD publish stage, propagating to a hard run "
        f"failure -- never a silent partial success, never merely SKIPPED_DUPLICATE), got "
        f"{results[mass_delete_filename]['status']!r}"
    )

    after_snapshot = _customer_current_state_snapshot(analytics_connection, removed_customer_ids)
    assert after_snapshot == before_snapshot, (
        f"expected gold state (event_ts, version_count) for every removed member to be "
        f"BYTE-FOR-BYTE unchanged by the FAILED run -- proving MassDeleteCircuitBreaker is a "
        f"PRE-mutation barrier stage, not a partial-apply-then-fail race. "
        f"before={before_snapshot!r} after={after_snapshot!r}"
    )
